### ISSUE TITLE
Too many changepoints returned for approximate search methods?

### ISSUE THREAD

**Issue by joelostblom** [deepcharles/ruptures#10]
Thanks for making all these changepoint detection methods available in Python!

When I try the examples from the docs for the approximate search method, e.g. `Window().predict()`, the number of breakpoints returned is one more than the number specified. The final breakpoint is always the index of the last observation in the timeseries. For example, if I run

``` python
import numpy as np
import matplotlib.pylab as plt
import ruptures as rpt
# creation of data
n, dim = 500, 3  # number of samples, dimension
n_bkps, sigma = 3, 5  # number of change points, noise standart deviation
signal, bkps = rpt.pw_constant(n, dim, n_bkps, noise_std=sigma)

model = "l2"  # "l1", "rbf", "linear", "normal", "ar"
algo = rpt.Window(width=40, model=model).fit(signal)
my_bkps = algo.predict(n_bkps=3)
my_bkps
```

`my_bkps` will actually consist of four values: `[120, 250, 375, 500]`, rather than three as specified with `n_bkps=3`. `500` is the length of `signal` in this case. Is this last returned value a real changepoint, or is it there for some other reason (e.g. a helper value for drawing the filled areas with `show.display()`)?

**Comment by dcdenu4** [comment]
The last returned value is just the number of samples from the signal. I had this same question awhile back, and when I looked through the source I came upon a comment about why this was occurring. I can not seem to find that comment now... but at the time I was apparently satisfied with the reason. I'll try to dig it up.

**Comment by deepcharles** [comment]
As mentioned by @dcdenu4, the last returned value is indeed equal to the number of samples. I choose this convention because in many functions, the signal length must be known. This is instead of having an additional parameter to functions. You can see the returned indexes as the ends of each regime.

**Comment by joelostblom** [comment]
Thanks for the replies @dcdenu4 and @deepcharles, I will always ignore the last value when plotting and performing calculations with the changepoints then.
