### ISSUE TITLE
Online changepoint detection (continued)

### ISSUE THREAD

**Issue by TMiguelT** [deepcharles/ruptures#109]
I've read through #3. Here it was mentioned that the sliding window search methods can be used for online detection. I've vaguely read some things suggesting that PELT and the kernel based search can be used for online detection. Is that true for the ruptures implementations? If yes, is there any interest in adding some useful utilities to ruptures to support this, namely some benchmarking metrics like time to detection/false alarm and ROC curves, as well as some documentation on online detection?

**Comment by deepcharles** [comment]
Thanks for this issue.

> PELT and the kernel based search can be used for online detection. Is that true for the ruptures implementations?

No, in ruptures, all methods takes the complete signal as input. To add online algorithms, one would need to add a detection base class with a different API, replacing the `.fit` and `.predict` methods with the following methods:
- `.fit_batch(batch_of_new_samples)`: to be called whenever new data points are available;
- `.predict_last_change()`: if a change has been detected, return the change point index.

It would be interesting to add a simple online method to see what would be the best API. Ideally something taken from a well cited article. However online methods are not our priority right now.
