### ISSUE TITLE
Warn when missing values in the signal

### ISSUE THREAD

**Issue by antvig** [deepcharles/ruptures#122]
Hi, 

First, thanks for this very great lib !

Just a small suggestion, it would be very helpfull to warn when there is NaN/null values in the signal.

I had missing values in my signal, I get results but really unexpected chgt point detected. I realized after couple of hours of exploration that it was due to missing values in my signal !

Antoine

**Comment by oboulant** [comment]
Hi, 

Thanks for you interest in `ruptures` !

In order for us to consider and investigate the issue, we would need a code sample and the setup information so we can reproduce the unexpected behavior. Could you please provide us with such information ? 

Thanks again for your interest !

**Comment by deepcharles** [comment]
We'll certainly add a warning in the documentation, thanks.

Adding a check on all inputs to checks for NaNs might be too much work for this issue. Besides, some future cost functions might accomodate NaNs.
