### ISSUE TITLE
[Question] Complex penalties

### ISSUE THREAD

**Issue by TMiguelT** [deepcharles/ruptures#129]
I note in the paper you talk about different penalties in section 6.1. However from looking through the library, it seems that ruptures only supports a fixed linear penalty (ie Beta). Am I right to assume that it doesn't work with more complex penalties linear such as AIC?

Further, if I wanted to implement a method were you normally would calculate a p-value of splitting (ie a likelihood ratio test following Chi squared), is the idea that we just have the `error()` method return the test statistic without testing for significance (ie the raw likelihood ratio), and the penalty constant implies a p-value? I suppose this makes segmentation fast and flexible, but highly dependent on the choice of penalty.

**Comment by oboulant** [comment]
Hi, 

Thanks for your interest in `ruptures` !

Since this is more of a question/discussion, could you please move this to the [discussions section](https://github.com/deepcharles/ruptures/discussions) ?

Thanks and see you there,

Olivier

**Comment by TMiguelT** [comment]
Done.
