### ISSUE TITLE
Detect only increasing trends or changes

### ISSUE THREAD

**Issue by mancunian1792** [deepcharles/ruptures#13]
Is there a way in the current scheme to detect only positive changes ?

Currently , am using window method.
``` python
def rupture_changepoint(points):
    points.values.reshape((points.shape[0],1))
    points = points.dropna()
    model = "l2"
    algo = rpt.Window(width = 10, model=model).fit(points.values)
    my_bkps = algo.predict(pen=60)
    print(my_bkps)
    fig, (ax,) = rpt.display(points, my_bkps, my_bkps, figsize=(10,6))
    plt.show()
```
Got the break points as [30, 40, 50, 100, 121]

![16121339](https://user-images.githubusercontent.com/9761766/66347419-4d817380-e922-11e9-8ac8-d2e076f1c38b.png)

Here, i dont want the decreasing trend to be there as a breakpoint. I am only interested in the [40,50] change. 

Please point me to the specific files that needs to be changed if its not straightforward

Thank you,

**Comment by mancunian1792** [comment]
Also, i dont have the true changepoints and hence gave the same as the predicted breakpoints.

**Comment by siebeniris** [comment]
Is this repo still being maintained?

**Comment by deepcharles** [comment]
It was not for a few months last year but now, it is (and will be for a good while).

Are you interested in this feature?

**Comment by TMiguelT** [comment]
Not the original poster but if this is possible without too much effort it certainly would be useful. 

I'm guessing it might be hard to distinguish trends vs mean shifts using these models (although that would also be useful), but is increase vs decrease something they can distinguish?

**Comment by deepcharles** [comment]
It is possible to implement this feature for window-based detection without much effort. I would create a custom search method for this. (For other methods, this might require more work.)

I will post a possible implementation shortly.

**Comment by divyagupta25** [comment]
I was using the PELT search method and had a similar requirement. Compared the average values of adjacent segments to identify whether the change point was indicating a positive or negative trend

**Comment by deepcharles** [comment]
Hello,

I am not sure how to do it with PELT. For Window, Binseg and BottomUp, it could be done but it requires a bit of work and I am not sure the results would be significant.
Do you have a reference to an article that describes what you are looking for?

**Comment by Nishants64** [comment]
Hi Charles, do you think this feature could be implemented? I am looking to identify downward trends and see that there was some discussion around this a few months ago. 

Thanks,
Nishant

**Comment by deepcharles** [comment]
Hello, I found [a recent article](https://www.jmlr.org/papers/volume21/18-843/18-843.pdf) that implements this kind of change point detection (as well as a more general type of constraints).
It would require some work though. I will try at the end of January if I can.

**Comment by deepcharles** [comment]
Closing for now.
