### ISSUE TITLE
Detecting mean change points

### ISSUE THREAD

**Issue by rahulsinghalmrt** [deepcharles/ruptures#133]
Hello Charles,

Thanks for putting this library together. I am trying to familiarize myself with how the library works and tried a few basic examples. I am keen on detecting mean change points. However, not sure if I am setting any parameter incorrectly to get below output.

```
import ruptures as rpt
ts = np.array(22*[ 500.] + 13*[1100.]) # Tried a few other timeseries of actual data.
algo = rpt.Dynp(model='l2').fit(ts) # Tried changing to l1 model and other methods too.
bkps = algo.predict(n_bkps=2)
rpt.display(ts, rs)
```
![image](https://user-images.githubusercontent.com/76267137/110226648-f7cf4300-7ee8-11eb-97bd-df0850c80590.png)

Best,
Rahul

**Comment by deepcharles** [comment]
Hi Rahul,

Your code is mostly good, except for two things:
- `bkps = algo.predict(n_bkps=2)`: if you have one change you can set `n_bkps=1` instead;
- `rpt.display(ts, rs)`: the variable `rs` is not defined, you should replace `rs` by `bkps`.

Cheers

**Comment by rahulsinghalmrt** [comment]
Hi Charles,
Thanks for pointing these out. I am trying to automate detection of level shifts in my program. These are timeseries of varying length. Thus I don't know for sure how many change points there would be. Based on above I am assuming it is best to do some sort of binary search on sub-series to find single `bkps` until some criteria is met (say two sub-series are not statistically different when compared on mean/stdev) . Or perhaps you recommend some better way  to use ruptures.
Also, the point detected with single `bkps` is a few points before the actual point.
Best,
Rahul

**Comment by deepcharles** [comment]
The procedure you propose could very well work. You could also perform "penalized change point detection". See Sections 2.2 and 5.1.2 of [the associated article](https://charles.doffy.net/files/sp-review-2020.pdf) for more details.

Here is a code snippet.

```python
algo = rpt.KernelCPD(kernel="linear", min_size=2).fit(signal)  # same as rpt.Dynp(model="l2"), but written in C
beta = 10  # to calibrate according to your needs
predicted_bkps = algo.predict(pen=beta)  # instead of algo.predict(n_bkps=...)
```

The value of `beta` controls the trade-off between the number of changes and the approximation error (higher beta, less change points). Usually, `beta` is set as a multiple of `log(T)*sigma**2` (where `T` is the number of samples and `sigma` is an estimate of the noise variance).

>  Also, the point detected with single bkps is a few points before the actual point.

By default, `rpt.Dynp(model="l2")` searches changes points in indexes that are multiples of 5 (to reduce the computational time). Use instead `rpt.KernelCPD` or set `rpt.Dynp(model="l2", jump=1)`. Note also that regimes also have a minimum length of two samples by default.

Charles

**Comment by rahulsinghalmrt** [comment]
Thanks Charles this is very helpful.
