### ISSUE TITLE
import problem - incompatibility with numpy

### ISSUE THREAD

**Issue by rsatijaUT** [deepcharles/ruptures#141]
I am using `python 3.7.6` and have installed the ruptures module in my conda environment:
`
(mytfenv) rohitpro@rohits-mbp-64 Phi29MATLAB-master % python -m pip install ruptures
Requirement already satisfied: ruptures in /Users/rohitpro/opt/anaconda3/envs/mytfenv/lib/python3.7/site-packages (1.1.3)
Requirement already satisfied: scipy in /Users/rohitpro/opt/anaconda3/envs/mytfenv/lib/python3.7/site-packages (from ruptures) (1.6.1)
Requirement already satisfied: numpy in /Users/rohitpro/opt/anaconda3/envs/mytfenv/lib/python3.7/site-packages (from ruptures) (1.20.1)
`

When I try to import the ruptures module in a jupyter notebook, I get a nasty attribute error (showing only the last line here):

`import ruptures as rpt`
`AttributeError: module 'numpy.linalg.lapack_lite' has no attribute '_ilp64'`

I tried uninstalling and reinstalling numpy and ruptures but the problem didn't resolve. How can I solve this issue?

**Comment by deepcharles** [comment]
I am not sure what causes this error.

Can you uninstall/install numpy then do the same with ruptures?

Also, can you provide the installed versions of numpy and ruptures?

Thanks

**Comment by rsatijaUT** [comment]
ah, it seems there was indeed a version error. The following command to reinstall numpy did the trick:

`sudo pip install numpy --ignore-installed numpy `

Thanks! You may close this ticket.
