### ISSUE TITLE
C segmentation fault on some inputs

### ISSUE THREAD

**Issue by DeanLa** [deepcharles/ruptures#143]
Minimal example:
```python
In [1]: import numpy as np
   ...: import ruptures as rpt
   ...: signal = np.array([720.1, 720.1, 1800.2, 360.0, 9361.0])
   ...: algo = rpt.KernelCPD(kernel="rbf", min_size=10).fit(signal)
   ...: cps = algo.predict(pen=10)
```
`[1]    63503 segmentation fault (core dumped)  ipython`

I realized this is probably because the `signal` is less than the min_size (longer signals don't cause that), but in that case, I would expect to get a meaningful python error which I can `try-except`. The C-level errors cause really unexpected behavior for example killed kernel on jupyter notebooks.

`ruptures==1.1.2`

**Comment by oboulant** [comment]
Hi!

Thanks a lot for you interest in `ruptures` !

This behavior has indeed already been reported to us in issue [123](https://github.com/deepcharles/ruptures/issues/123). 

It has been solve in PR [128](https://github.com/deepcharles/ruptures/pull/128) and should be included in the next release 📦  

FYI, in you particular case, you will have the following message :

```python
File "<stdin>", line 1, in <module>
  File "[...]/ruptures/detection/kernelcpd.py", line 107, in predict
    raise BadSegmentationParameters
ruptures.exceptions.BadSegmentationParameters
```

Hope it helps !

Olivier
