### ISSUE TITLE
Feature request: Cost function equivalent to R changepoint library  cpt_meanvar 

### ISSUE THREAD

**Issue by drandynisbet** [deepcharles/ruptures#148]
Hi,
apologies in advance if I've missed something obvious, I'm using ruptures more as a black-box user - and have only started to dabble with changepoint analysis relatively recently. Could you outline what's required to implement, or whether you might release support for a cost-function covering both mean and variance that would give similar results to the R cpt_meanvar? 
I'm using PELT to examine some observations from tracing the performance of applications when  they are in execution. 

Thanks,
Andy

**Comment by oboulant** [comment]
Hi @drandynisbet ,

Thanks for you interest in `ruptures` !

Why not checking for instance [Cost Normal](https://centre-borelli.github.io/ruptures-docs/user-guide/costs/costnormal/) that do detect changes in the mean and covariance matrix of a sequence of multivariate Gaussian random variables ? 

For instance :

```python
import ruptures as rpt
import numpy as np
from numpy.random import RandomState
import matplotlib.pyplot as plt  # for display purposes

rd = RandomState(1234)
segment_length = 100

signal = np.r_[rd.normal(0, 0.1, segment_length), 
        rd.normal(0, 0.01, segment_length),
        rd.normal(1, 0.05, segment_length)]


algo = rpt.Pelt(model="normal", min_size=1, jump=1).fit(signal)
my_bkps = algo.predict(pen=100)
print(my_bkps)

fig, ax = rpt.display(signal, [100, 200, 300], my_bkps)
plt.show()
```

Which outputs :
![Figure_1](https://user-images.githubusercontent.com/12909374/115297410-76f89d80-a15c-11eb-9e82-a0ec04945697.png)

**Comment by deepcharles** [comment]
As mentionned by @oboulant, this cost function will simultaneously detect changes in the mean and variance/covariance matrix for multidimensional signals. This should emulate the behaviour of `cpt_meanvar`.

**Comment by oboulant** [comment]
I am closing the issue. Feel free re-open one or a discussion thread if needed !
