### ISSUE TITLE
Weird behaviour correction when median(K) = 0 

### ISSUE THREAD

**Issue by guillaumeGilles98** [deepcharles/ruptures#15]
During some different tests, we experiment a weird behaviour with PELT (RBF cost function)When median(K) is equal to 0, the segmentation is clearly weird : each segment have an equal length (5).To experiment this you can run the following code
```python
import ruptures
import numpy as np
curve= [0, 528, 503, 0, 0, 0, 541, 542, 0, 542, 0, 0, 0, 542, 
             500, 530, 0, 0, 515, 0, 536, 0, 0, 539, 518, 0, 0, 530, 0, 0, 
             503, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
             0, 0, 0]
curve = np.array(curve)
algo = ruptures.Pelt(model='rbf', min_size=1).fit(curve)
seg = algo.predict(pen=1)
ruptures.display(curve, seg)
```
Which leads to this segmentation :
![rupture_error_segmentation](https://user-images.githubusercontent.com/56997675/67569577-88abe100-f72f-11e9-8059-cb59d6c147e4.png)

**Comment by deepcharles** [comment]
Closed by #14
