### ISSUE TITLE
Request for documentation to annotate changepoint

### ISSUE THREAD

**Issue by schetudiante** [deepcharles/ruptures#150]
Hey Ruptures Team,
Great work with the package I am a beginner and I can't find good documentation to help me annotate the changepoints (dates) in my changepoint pelt plot using raptures. 
PS. top 4 ranked changepoints is what I need.

Currently I use the following code:
`algo = rpt.Pelt(model = 'rbf').fit(points)`
`bkps = algo.predict(pen = 10)`
`plt.title('Change Point Detection: Pelt Search Method')`
`rpt.show.display(points, bkps, figsize=(17, 6))`
`plt.savefig('1rpt_plot.png',dpi=80)`

which gives me a plot like this 
![1rpt_plot](https://user-images.githubusercontent.com/82269015/115725211-ee5b4680-a381-11eb-92a3-45dea2b2a4bf.png)

There are 3 problems in this , 
a) The x axis is not showing dates
b) I have no idea which changepoints are the top 4 changepoints and 
c) to annotate them

Could you provide a small code example , my dataset looks like this toy dataset. It would really help me!

Date, Value
2016-01-03 , 286
2016-01-04 , 83
2016-01-05 , 112
2016-01-06 , 286
2016-01-06 , 286
2016-01-07 , 379
2016-01-08 , 286
2016-01-09 , 120
2016-01-08 , 85
2016-01-09 , 300

Thanks :)

**Comment by deepcharles** [comment]
Thanks for your interest in ruptures.

> a) The x axis is not showing dates

This is more a question of matplotlib and there are many different ways to do it, depending on what your objective is (see for instance [this function](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.plot_date.html) or [this SO question](https://stackoverflow.com/questions/32972371/how-to-show-date-and-time-on-x-axis-in-matplotlib)).

> b) I have no idea which changepoints are the top 4 changepoints

It is not clear what can be defined as the *top* change points.

> c) to annotate them

Again this is a question of matplotlib manipulations, and really depends on your objective.

**Comment by deepcharles** [comment]
(Feel free to reopen.)
