### ISSUE TITLE
Compare Two Plots

### ISSUE THREAD

**Issue by thebadguyfromstarwars** [deepcharles/ruptures#152]
Hello there,

I wanted to use ruptures as a trend analysis tool to compare forecasted and histroical data - using the histroical data as a template for accuracy. Is it possible to compare two plots/objects and get correlation metrics?

**Comment by deepcharles** [comment]
Thanks for your interest in ruptures.

Do you want to plot the two signals side by side? Or on the same plot?

As for the correlation, [`numpy.correlate`](https://numpy.org/doc/stable/reference/generated/numpy.correlate.html) should do the trick I think.

**Comment by GuillaumeWrobel** [comment]
+1 for `numpy.correlate` with the `full` mode IIRC.
