### ISSUE TITLE
Create subplots 

### ISSUE THREAD

**Issue by amaliavog** [deepcharles/ruptures#156]
Hello everyone, 

I would like to create a grid of 5 rows and 2 columns and use display() function to show the subplots and then edit the axes and titles with matplotlib. Is there a way to do it?

Thank you in advance

**Comment by deepcharles** [comment]
Hello,

The `display` function cannot do much customization. The best way for you is to copy and adapt its [code](https://github.com/deepcharles/ruptures/blob/master/src/ruptures/show/display.py).
