### ISSUE TITLE
L1 Cost function for KernelCPD

### ISSUE THREAD

**Issue by samuelreh** [deepcharles/ruptures#159]
Is it possible to use the L1 cost function with the KernelCPD? If not, is this something I would be able to contribute. It would be useful for a project I'm currently working on.

**Comment by deepcharles** [comment]
Hello,

Currently it is not possible, because the L1 cost function does not derive from a kernel. It would be indeed instresting to have the L1 cost function coded in C. If you start a pull request, I would be glad to help.

**Comment by deepcharles** [comment]
Closing now. Feel free to reopen.
