### ISSUE TITLE
Small window sizes throw errors

### ISSUE THREAD

**Issue by kathapand** [deepcharles/ruptures#16]
Hello!
I am using ruptures to detect change points in morphologic time series, e.g. [ts.txt](https://github.com/deepcharles/ruptures/files/3858828/ts.txt)
In my original application, the CPD method works fine. Now I am testing the influence of reduced temporal resolution and therefore simultaneously reduced window size in the change point detection. However, this throws an error when `width<10`. It is not clear to me why this should not work. Could this be a bug, that some dependent value is calculated too small? Shouldn't the calculation of median deviation work down to window sizes of >=3?

My code using [ts.txt](https://github.com/deepcharles/ruptures/files/3858828/ts.txt) is, e.g.:
```
import numpy as np
import ruptures as rpt
import matplotlib.pyplot as plt

ts1d = np.loadtxt('ts.txt')

winsize=10 # smallest value that works
# winsize=6 # throws an error

algo = rpt.Window(width=winsize, model='l1', min_size=1).fit(ts1d)
breakpoints = algo.predict(pen=1.0)

rpt.show.display(ts1d, [], breakpoints,figsize=plt.figaspect(0.5))
plt.show()
```
If I reduce the width (winsize), the error is:

```
  File "C:\Python36\lib\site-packages\ruptures\detection\window.py", line 262, in predict
    bkps = self._seg(n_bkps=n_bkps, pen=pen, epsilon=epsilon)
  File "C:\Python36\lib\site-packages\ruptures\detection\window.py", line 175, in _seg
    mode="wrap")
  File "C:\Python36\lib\site-packages\scipy\signal\_peak_finding.py", line 177, in argrelmax
    return argrelextrema(data, np.greater, axis, order, mode)
  File "C:\Python36\lib\site-packages\scipy\signal\_peak_finding.py", line 232, in argrelextrema
    axis, order, mode)
  File "C:\Python36\lib\site-packages\scipy\signal\_peak_finding.py", line 58, in _boolrelextrema
    raise ValueError('Order must be an int >= 1')
ValueError: Order must be an int >= 1
```
I would appreciate any hint, what might be the issue here. And thanks for the useful change point detection package!

**Comment by TrentonBush** [comment]
I ran into the same issue and found that it is caused by the 'jump' parameter. It has a default value of 5. Manually setting jump=1 let me work with window sizes as low as 4.

I don't think the jump parameter _should_ affect the acceptable window sizes, but it does. Looks like a bug.

**Comment by kathapand** [comment]
Thank you for this hint! Setting the jump-parameter makes it work as described.
I will just set the jump parameter to the given width-value then in my function call. This could also be a suitable solution for a fix of this issue.

**Comment by deepcharles** [comment]
Yes that was a bug. I have fixed it now.
