### ISSUE TITLE
Definition of the Dynp function

### ISSUE THREAD

**Issue by mackancurtaincheeks** [deepcharles/ruptures#161]
Is there any definition, or pseudocode, of the Dynp function? I can't seem to find anything except for a brief explanation in text.

**Comment by mackancurtaincheeks** [comment]
.. because even when I am reading through the article no definition of the dynp function is given, only a discussion between two possible dynamical programming algorithms. I would like to use this is my bachelor thesis and therefore I kind of need to define the function Dynp.

**Comment by deepcharles** [comment]
[In the related article](https://charles.doffy.net/files/sp-review-2020.pdf) there is a pseudo-code for the Dynp function. This is not exactly the one implemented in ruptures, but both are strictly equivalent. You can find it on page 11.

**Comment by deepcharles** [comment]
Closing now. Feel free to reopen.
