### ISSUE TITLE
CostAR modifies signal in-place

### ISSUE THREAD

**Issue by robert-lieck** [deepcharles/ruptures#162]
Using CostAR with Pelt (I assume also with other search methods) modifies the provided signal in-place. That is, when providing a numpy array as a signal, the original data will be manipulated. Of course, making an explicit copy of the data before calling fit prevents this, but I feel this should not be expected or be _very_ prominently mentioned in the documentation.

To give you an idea, here is a screen shot. I looks like the first couple of points are replaced by their mean or something:

![image](https://user-images.githubusercontent.com/16177217/119356113-5c0ed100-bca6-11eb-85cb-89a31ec4dfce.png)

**Comment by deepcharles** [comment]
Hello,

Indeed this is bad practice. I'll look into that. Thanks

**Comment by robert-lieck** [comment]
Oh, that's why your issues list is so short... 😄 Impressive time to respond and fix, many thanks!

Great library by the way and very useful for the evaluation of new methods. Hope to be able to express my gratitude by providing another citation shortly 😉
