### ISSUE TITLE
Implementing c_rank cost function

### ISSUE THREAD

**Issue by TMiguelT** [deepcharles/ruptures#17]
Thanks for your great work with this library.

I notice that table 2 in the paper says that the Lévy-Leduc paper (citation 28) is implemented in `ruptures`, but it doesn't seem that a `c_rank` cost function is implemented. Is this correct?

Are you interested in adding this cost function to `ruptures`? Would you accept a PR adding it?

**Comment by deepcharles** [comment]
Indeed, the `c_rank`cost function is not implemented.
That would be a great addition! Don't hesitate to message me, I would be happy to participate.
