### ISSUE TITLE
Add support to release aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [deepcharles/ruptures#179]
Problem
---------
On aarch64, 'pip install ruptures' builds the wheels from source code and then install it. It requires user to have development environment installed on his system. Also, it takes some time to build the wheels than downloading and extracting the wheels from PyPi.

Resolution
-----------
On aarch64, 'pip install ruptures' should download the wheels from PyPi

@julia-shenshina, Please let me know your interest on releasing aarch64 wheels. I can help in this.

**Comment by oboulant** [comment]
Closing the issues since it has been merged in https://github.com/deepcharles/ruptures/pull/180
