### ISSUE TITLE
Ensemble methods for change point detection

### ISSUE THREAD

**Issue by siebert-julien** [deepcharles/ruptures#183]
Hi,

I wanted to know first if you were aware of the following work (the authors use ruptures) and if there were any plans of implementing ensemble methods for CPD in ruptures?

Katser, I.; Kozitsin, V.; Lobachev, V.; Maksimov, I. Unsupervised Offline Changepoint Detection Ensembles. Appl. Sci. 2021, 11, 4280. https://doi.org/10.3390/app11094280 

PDF: https://www.mdpi.com/2076-3417/11/9/4280
Code: https://github.com/YKatser/CPDE

I think this is also related to issue #5 

I also wanted to get your thoughts on using multiple cost functions in parallel. In the paper, the authors try to improve the performance of the detection. On my side, I am less interested in finding the change points than in trying to characterize them. 

For example I have been doing some experiments applying the l2 cost function together with a sliding window approach with different windows lengths in parallel to characterize the scales of the change-in-mean (a little bit like a wavelet analysis).

I am wondering I someone already apply the same approach (I was not able to find any paper) and I think one could use different cost functions in parallel to get more information about the types of change (for example: change in mean and change in variance happening together).

Thx,

Julien

**Comment by deepcharles** [comment]
Hello, many thanks for the reference, it seems indeed a good fit for the ruptures library.

I will look at it over the summer.

As for you second question (the multiscale analysis), there are several authors who work on it; see for instance SMUCE [1]. The article is mainly theoretical but they propose a ready-to-use R implementation. 

[1] Frick, K., Munk, A., & Sieling, H. (2014). Multiscale change point inference. Journal of the Royal Statistical Society. Series B: Statistical Methodology, 76(3), 495–580.

**Comment by siebert-julien** [comment]
@deepcharles Thanks for the prompt reply and the link to the paper.

Merci!
