### ISSUE TITLE
PELT Multivariate implementation

### ISSUE THREAD

**Issue by Irfanwustl** [deepcharles/ruptures#187]
Thanks a lot for this great tool. In [the review paper](https://www.sciencedirect.com/science/article/pii/S0165168419303494) it is mentioned that ruptures can work on both univariate and multivariate data. I am using PELT from ruptures.  I think the PELT paper referred by ruptures is for univariate data. How is the multivariate version of PELT implemented here?

**Comment by deepcharles** [comment]
Hello,

You can apply PELT on your multivariate signal the same way you would if the signal was univariate. Just be careful that multivariate signals must have shape (n_samples, n_dims).

Cheers

**Comment by Irfanwustl** [comment]
Yes. I have applied it and it is working. However, as I am going to write a paper on my project and will cite the ruptures library, I  wanted to know how you extend PELT from univariate to multivariate. If I understand correctly, the PELT paper you referred is for univariate data (though the PELT authors have published [a recent algorithm](https://link.springer.com/article/10.1007/s11222-020-09940-y) for the multivariate case)

**Comment by deepcharles** [comment]
If you use the L2 cost, then the cost function is given in Equation C2. And it works in the multivariate setting. It detects change of means only.

In the article you mentioned, the cost function can also cope with multivariate data, but is more complex and currently not implemented.

**Comment by deepcharles** [comment]
Closing now. Feel free to reopen.
