### ISSUE TITLE
Too strict sanity check for Pelt model?

### ISSUE THREAD

**Issue by ChiQiao** [deepcharles/ruptures#188]
Sanity check was added in v1.1.4 for the `Pelt` class, and raises a `BadSegmentationParameters` for the example below
```Python
import ruptures
import numpy as np

model = ruptures.Pelt(min_size=5, jump=1)
model.fit(np.ones(9))
model.predict(pen=0)
```

For a signal with a length of 9, `min_size=5` makes sense to me and in v1.1.3 it returns `[9]`. I wonder if the sanity check is too strict?

**Comment by oboulant** [comment]
Hi,

Thanks for your interest in `ruptures` ! 

Here, you are giving as an input 

* a signal with 9 samples
* a segment minimum size of 5 samples
* a jump size of 1 sample

With those parameters, the sanity checks verify that it can generate at least 2 segments (ie. 1 break point). Here, what you are presently asking is not feasible, indeed : 

* You would need 10 samples in total to generate two segments with at least 5 samples in each

### Walkthrough in the Source Code

* As for the Pelt detection method, Sanity check is call at predict time [here](https://github.com/deepcharles/ruptures/blob/d211c5c6257722aefafa81499a3171f1bf42a6a7/src/ruptures/detection/pelt.py#L124)
* The sanity check is implemented [here](https://github.com/deepcharles/ruptures/blob/d211c5c6257722aefafa81499a3171f1bf42a6a7/src/ruptures/utils/utils.py#L32). It basically checks that it has enough points in an input signal of size `n_samples` to find the asked number of break points (`n_bkps`) for some given segment minimum size (`min_size`) and jump size (`jump`). 

### Alternatives for you situation
In your case, the following choices would work : 

```python
model = ruptures.Pelt(min_size=5, jump=1)
model.fit(np.ones(10))
model.predict(pen=0)
```

```python
model = ruptures.Pelt(min_size=4, jump=1)
model.fit(np.ones(9))
model.predict(pen=0)
```

```python
model = ruptures.Pelt(min_size=5, jump=2)
model.fit(np.ones(11))
model.predict(pen=0)
```

**Comment by deepcharles** [comment]
@ChiQiao Indeed it makes sense to return `[9]`. We will see how this change propagates through the rest of the package.

Thanks

**Comment by oboulant** [comment]
Oh, did not pay attention to the `Pelt` mention and the detection methods that may return 0 break point (even more with a 0 penalty). 
Will look into it !
