### ISSUE TITLE
min_size

### ISSUE THREAD

**Issue by amessica** [deepcharles/ruptures#19]
min_size is not working for me  when using, for example:
algo = rpt.Window(width=10, model='l2', min_size = 40).fit(signal)
my_bkps = algo.predict(n_bkps=4)

I get segments < 40 even though min_size = 40
I am using a 1D time series - numpy array -  of  a stock's close prices (array length of 796) that were loaded from a CSV file into pandas dataframe such that:

signal = pandas.dataframe['close'].values

**Comment by deepcharles** [comment]
Hello,

Indeed this is a bug. In its current form, `Window.predict` search for score maximums in region of 
at least `min_size` samples while it should search regions of at least `2*min_size`.

https://github.com/deepcharles/ruptures/blob/b5879fb8ad767916d98b13e9b8da022d947b334c/ruptures/detection/window.py#L173-L176

I will change it now.

**Comment by amessica** [comment]
Great,
Will you issue an upgrade or should I modify in myself?
On another note, are you familiar with a CPD algorithm for 2D data (e.g.
applied for an image or heat map and the like).
I guess, it would act as an edge detector....
Cheers,
Avi

**Comment by deepcharles** [comment]
It is already upgraded in the pypi version of the package (` pip install --upgrade ruptures` should do the trick).

> On another note, are you familiar with a CPD algorithm for 2D data

Indeed, for 2D data, this is an edge detector, which is a well-studied subject on its own. There is [this review (with code)](http://www.ipol.im/pub/art/2015/35/) that might guide you.

**Comment by amessica** [comment]
Thx.
You are top notch!
Good luck with your Ph.D
Avi
