### ISSUE TITLE
Detection advice 

### ISSUE THREAD

**Issue by RobertoDF** [deepcharles/ruptures#197]
Hi,
I've been trying different search methods and models on the following dataset. For example:
```
model = "rank"  # "l1", "rbf", "linear", "normal", "ar",...
algo = rpt.Binseg(model=model, jump=50).fit(behavior["Running speed"].rolling(1000,center=True).mean().values)
limits = algo.predict(pen=1000)
```
![Screenshot 2021-09-06 at 18 37 23](https://user-images.githubusercontent.com/37729096/132245541-4553f858-5f2c-4de1-9926-a6b116b6cd7d.png)

I couldn't reach a good enough result, can somebody point at what would be a good direction? 
[test_data_pickle](https://www.dropbox.com/s/50eyxinlxzadurw/test_data.pkl?dl=0)

**Comment by oboulant** [comment]
Hi @RobertoDF ,

Thanks for your interest in `ruptures` !

Closing this since it is not an issue, rather a discussion. Feel free to open a thread in the [discussion section](https://github.com/deepcharles/ruptures/discussions).

**Comment by RobertoDF** [comment]
Sorry for the misplacement! I
