### ISSUE TITLE
It's now possible to install via conda. Update README

### ISSUE THREAD

**Issue by rpanai** [deepcharles/ruptures#21]
I created a conda-forge recipe and my [PR](https://github.com/conda-forge/staged-recipes/pull/10930) is merged so you can install this package with conda [link](https://anaconda.org/conda-forge/ruptures) using

```
conda install -c conda-forge ruptures
```

You might consider to update the README accordingly.

**Comment by deepcharles** [comment]
Cool. Thank you very much! I will do it shortly.

**Comment by deepcharles** [comment]
Hello @rpanai,

Is it possible to update the version of conda-forge version of ruptures?

Regards,

Charles

**Comment by rpanai** [comment]
Hi @deepcharles,
it's already on [feedstock](https://github.com/conda-forge/ruptures-feedstock). I just need to review the automatic PR. Give me few minutes.

**Comment by rpanai** [comment]
@deepcharles here we are [ruptures 1.0.3](https://anaconda.org/conda-forge/ruptures). If you can please update the readme.
