### ISSUE TITLE
Return a group index with the same shape as the signal

### ISSUE THREAD

**Issue by Illviljan** [deepcharles/ruptures#232]
Once you have found the change points, you usually want to do some kind of operation (like `mean()`) on those groups of data within the change points. 

It's quite common to use pandas for that (`df.groupby("group_idx")`). But dataframes requires the group_idx to have the same shape as the signal. But `ruptures` return only the index in some kind of shape.

The suggestion is therefore to instead of returning a list of indexes to simply fill a group_idx array with the change point number and return that array, for example:
`[2, 5] -> [0, 0, 2, 2, 2, 5, 5]`

This could potentially improve performance as it's often faster to pre-allocate arrays with the correct size and fill in values rather than repeatedly changing the size of the array (when I've been benchmarking, `.append` has been one of the bottlenecks). 
Matlab has a nice [article](https://www.mathworks.com/help/matlab/matlab_prog/preallocating-arrays.html ) explaining it better than I could.

This is quite a breaking change so it probably has to be optional for a while.

Examples of packages using group_idx style:
[pandas ](https://github.com/pandas-dev/pandas)
[dask dataframes](https://github.com/dask/dask)
[numpy_groupies](https://github.com/ml31415/numpy-groupies)
[flox](https://github.com/dcherian/flox)

**Comment by deepcharles** [comment]
Hi, thanks for the nice suggestion. Indeed, this would be a breaking change. Nevertheless we could add an optional argument to change the output format.
