### ISSUE TITLE
AttributeError: module 'ruptures' has no attribute 'KernelCPD'

### ISSUE THREAD

**Issue by irischang020** [deepcharles/ruptures#233]
Hi,

I was going through the notebooks in examples.
For the performance comparison one, I got `AttributeError: module 'ruptures' has no attribute 'KernelCPD'`
https://github.com/deepcharles/ruptures/blob/master/docs/examples/kernel-cpd-performance-comparison.ipynb
Do you have any insights as to what could go wrong?

Thanks!

**Comment by deepcharles** [comment]
Hello,

Which version of ruptures are you using?

```python
import ruptures as rpt
print(rpt.__version__)
```

Thanks

**Comment by irischang020** [comment]
Hi,

I am using 1.1.6.

Thanks!

**Comment by deepcharles** [comment]
I cannot replicate this behaviour on my compute or on the online version of the notebook (see [here](https://centre-borelli.github.io/ruptures-docs/examples/kernel-cpd-performance-comparison/), click on the Binder link at the top).

Can you try removing/reinstalling the library?

**Comment by deepcharles** [comment]
Did it work? Feel free to reopen this issue.

**Comment by irischang020** [comment]
Yes, it worked. Thanks!
