### ISSUE TITLE
Relax GitHub Actions first time contributor approval

### ISSUE THREAD

**Issue by Illviljan** [deepcharles/ruptures#235]
A while back GitHub made it so that new contributors cannot trigger GitHub Actions workflows and a maintainer has to hit "Approve and Run" every time they push a commit to their PR. This is rather annoying for both the contributor and the maintainer as the back and forth takes time. 

This setting can be relaxed however, see:
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#configuring-required-approval-for-workflows-from-public-forks

**Comment by oboulant** [comment]
Hi @Illviljan ,

Thx for you interest in `ruptures` !

Nevertheless, we are quite happy with this behaviour since it allows to be parsimonious with GHA. 

Best !

**Comment by Illviljan** [comment]
I assume maintainers will be more active in the PR section then? Considering there are PRs there needing approvals.
