### ISSUE TITLE
How to select a proper method for detecting onset of signals?

### ISSUE THREAD

**Issue by yijun1994** [deepcharles/ruptures#239]
I have a need for detecting change point of seismic waves, the onset seem quite obvious by visual inspection.
But costAR and costL2 seem failed to detect the change point. Could you give me some suggestions about how to select a proper cost function among presented ones?

**Comment by oboulant** [comment]
Hi @yijun1994 ,

Thx for your interest in `ruptures`. 

Would you have a visual graph of those data ? 

In the mean time, you can find in the documentation User Guide the list of all the cost function available in `ruptures` : https://centre-borelli.github.io/ruptures-docs/user-guide/

<img width="284" alt="Screenshot 2022-02-28 at 11 21 11" src="https://user-images.githubusercontent.com/12909374/155966543-6f347c91-3cd9-44c5-9b8b-afcf2df40903.png">

**Comment by yijun1994** [comment]
<img width="259" alt="截圖 2022-02-28 下午4 21 12" src="https://user-images.githubusercontent.com/100558277/155966903-997bb333-ec10-47f5-ba9b-120e3e5473d6.png">
The visual graph of some signal samples is displayed above. Actually, they are earthquake signals.

**Comment by deepcharles** [comment]
To detect changes in amplitude, you can use [`CostNormal`](https://centre-borelli.github.io/ruptures-docs/user-guide/costs/costnormal/). You can also transform you signal to only keep its enveloppe (see [here](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.hilbert.html)) and use `CostL2` on the transformed signal.

Hope this helps

**Comment by yijun1994** [comment]
Thanks! I also employed kernel-based (Gaussian) method to identify the change point. I found it useful but not so precise. 
I am wondering if the parameters I set is not right.
<img width="448" alt="截圖 2022-02-28 下午5 22 50" src="https://user-images.githubusercontent.com/100558277/155969126-b2b4d44e-bb20-417d-af79-b37744779d14.png">

**Comment by deepcharles** [comment]
The detected changes might not be at the exact location you want, because there is a small amplitude phase between the flat phase and the full amplitude phase. Some ah-hoc post-processing might be needed in any case.

**Comment by yijun1994** [comment]
is 'ah-hoc post-processing' a specific method in signal processing?

**Comment by deepcharles** [comment]
No, it is whatever method you can find to add more precision if the detected changes are a bit "off".

**Comment by deepcharles** [comment]
Closing for now. Feel free to reopen.
