### ISSUE TITLE
wild binary segmentation

### ISSUE THREAD

**Issue by christina-l-cleveland** [deepcharles/ruptures#252]
hello! I noticed in the documentation for your binary segmentation you reference a paper describing [wild binary segmentation](https://doi.org/10.1214/14-AOS1245) and was wondering if the method implemented in the package is the generic binary segmentation or wild binary segmentation. Thanks for the package!

**Comment by deepcharles** [comment]
Hello, the method implemented is the generic binary segmentation. Cheers.
