### ISSUE TITLE
Can ruptures detect change point of pulses?

### ISSUE THREAD

**Issue by elcolie** [deepcharles/ruptures#256]
I need to detect change point of 2 pulses. Here are the results I got from `rbf, l2, and l1`.
Can ruptures detect change point of pulses?

![image](https://user-images.githubusercontent.com/18206728/167339834-9ff560d4-606d-4f2c-953e-23cb85c8523d.png)
![image](https://user-images.githubusercontent.com/18206728/167339864-943e9383-7187-4f9e-aee4-e2350dbf94c1.png)
![image](https://user-images.githubusercontent.com/18206728/167339888-220449bd-e15e-4556-a995-b26763949e84.png)

**Comment by deepcharles** [comment]
Hi,

Sorry for the late reply. You can try the custom cost function defined [here](https://centre-borelli.github.io/ruptures-docs/user-guide/costs/costcustom/). You might have to set the baseline of the signal to 0 (`signal - signal.min()`).

A different approach would be to use the [peak finding procedure of scipy](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.find_peaks.html) with the appropriate parameters.

Hope this helps

**Comment by deepcharles** [comment]
Closing for now. Feel free to reopen.
