### ISSUE TITLE
Randindex overflow error

### ISSUE THREAD

**Issue by missrg11** [deepcharles/ruptures#266]
I have noticed that when working with long signals ( >150,000 samples), an overflow occurs on the Randindex calculations, resulting to negative value for disagreement and out-of-range value for Randindex. 

Not sure if this is due to system settings or general issue, however I would suggest slight adjustment to the code in order to avoid it. The issue does not occur when the order or the calculations changes. 

Hence, within the Randindex function to replace this:

`disagreement /= n_samples * (n_samples - 1) / 2`

with this:

`disagreement = (disagreement/n_samples) / (n_samples - 1) / 2`

**Comment by oboulant** [comment]
Hi @missrg11 ,

Thx for your interest in `ruptures` !

Could you share here a code snippet to reproduce the issue ? I would like to investigate this a bit deeper. 

Best !

**Comment by missrg11** [comment]
Hi, thanks for getting back to me on this. 

After investigating more on the issue, it had to do with the fact that the llists with breakpoints used as input arguments were `int32` rather than `int`. 

When the lists contain `int` elements, the existing code works just fine.

**Comment by oboulant** [comment]
Closing this issue for now ! Please feel free to reopen if needed !
