### ISSUE TITLE
Circular Binary segmentation  

### ISSUE THREAD

**Issue by rrazaghi** [deepcharles/ruptures#27]
Hi Charles, and thank you for this great tool. Currently, we do not have a robust implementation of CBS in python. Do you think this is a feasible thing to implement in ruptures?

Thanks a lot,
Roham

**Comment by deepcharles** [comment]
Hello, that would be a great addition. I am currently looking into ways to port methods implemented in R (in fact C or C++) to ruptures using Cython. If you have any experience in this, that would be appreciated. 
In the meantime, you can share R implementations of CBS that you find robust enough.

Charles

**Comment by rrazaghi** [comment]
Thank you Charles! I have not done that using Cython before but I know most of the packages just call Rscript within their pipeline to use this package: https://bioconductor.org/packages/release/bioc/html/DNAcopy.html

for example the famous CNVkit tool calls it using this script I believe :
https://github.com/etal/cnvkit/blob/fd3555256d2a5aa3978c475d19c88065be68c6c4/cnvlib/segmentation/cbs.py

I hope this is helpful and please let me know if I can help with anything else!

Thanks again for this very useful package.
Roham

**Comment by deepcharles** [comment]
Cool, I look into it.

Closing this issue for now.
