### ISSUE TITLE
[BUG] Two badges not rendering correctly in readme

### ISSUE THREAD

**Issue by darigovresearch** [deepcharles/ruptures#279]
See screenshot of readme

![image](https://user-images.githubusercontent.com/30328618/205488788-f0f27253-78e7-47ea-95e7-32442ed5e49e.png)

**Comment by deepcharles** [comment]
Thanks for bringing this issue to our attention. It has been fixed now.

**Comment by darigovresearch** [comment]
You're very welcome & thanks for the fix
