### ISSUE TITLE
Is it possible to calculate delta time?

### ISSUE THREAD

**Issue by bbartling** [deepcharles/ruptures#28]
Hi, 

I apologize in advance if this is a silly question, but I am attempting calculate in "hours" of electricity data daily load profiles the time it takes for rise & fall times in the data... For example this is a snip from a while paper on analyzing the data for building electricity demand.

![LoadProfSnip](https://user-images.githubusercontent.com/29737117/80019155-b2568280-849c-11ea-81df-022107865d72.PNG)

I think I can get sort of close using the Binary Segmentation search method [as shown in this Gist](https://gist.github.com/bbartling/17f0981ca9e37b9f5e79b648ba3a5692).

Can I calculate in hours the delta time between each change point? Any tips greatly appreciated thank you for creating a cool repo!

**Comment by deepcharles** [comment]
Hello,

Thanks for using `ruptures`.

As for your problem, you simply need to extract the original timestamps and compute a diff, as shown below:

```Python
# getting the timestamps of the change points
bkps_timestamps = df2.iloc[[0] + my_bkps[:-1] +[-1]].index
# computing the durations between change points
durations = (bkps_timestamps[1:] - bkps_timestamps[:-1])
# this is a TimedeltaIndex, so you can convert it to seconds
print(durations.seconds)
# or in hours
print(durations.seconds/60/60)
```

Hope that helps. Feel free to re-open this issue if you have any further question.

**Comment by bbartling** [comment]
Wow thanks works great... Im also in the process of learning dynamic programming (and hopefully some RL). If you have the time, could you explain a little bit about how the dynamic programming change point algorithm would work on an electricity dataset? I understand electricity and a little bit about basics of the bellman equation. Thanks again for your time...

**Comment by deepcharles** [comment]
I can only point you towards [my work](https://deepcharles.github.io/publication/sp-review-2020) where I discuss how dynamic programming is applied to change point detection. For the RL setting, the notations are quite different but the underlying idea is similar.
