### ISSUE TITLE
Implementing PCA based cost function

### ISSUE THREAD

**Issue by statefb** [deepcharles/ruptures#29]
Thank you for making this amazing library.

I'm engaging in manufacturing industry and I found that PCA (Principal component analysis) based segmentation algorithm is useful for sensor data in this field.

PCA based segmentation is realized by two types of cost function: Q statistics and T2 statistics.
Q statistics is so-called reconstruction error of PCA and T2 is hotelling's T-squared.
[Here is original paper (pp. 12-15)](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.853.2380&rep=rep1&type=pdf) and it says:

> The Q reconstruction error can be used to segment the time-series according to the direct change of the correlation  between  the  variables,  while  the  Hotelling's  T2  statistics  can  be  utilized  to  segment  the  time-series based on the drift of the center of the operating region. 

Indeed, ruptures already has mahalanobis implementation which computes cost function by using global structure i.e. inverse of covariance of entire signal. The difference is the paper's method computes inv cov matrix of each segment signal on subdimension at every iteration.

I'd like to ask you if interested in adding these cost function to ruptures and accept PR.
Thank you in advance!

**Comment by deepcharles** [comment]
Hello, of course PR are welcome. Do not hesitate to post even a sub-optimal method, so I can also work on it.

**Comment by statefb** [comment]
Thank you for response. I'll send PR later.
