### ISSUE TITLE
Online algorithms?

### ISSUE THREAD

**Issue by juliensiebert** [deepcharles/ruptures#3]
Hi (bonjour),

I am a bit of newbie in changepoint detection algorithms, I wanted to know if it is possible to use ruptures for online detection? So far I have the (probably false) impression that it focuses only on offline detection.

Am I right? 

All the best,

Julien

**Comment by juliensiebert** [comment]
I think this answers my own question

http://ctruong.perso.math.cnrs.fr/ruptures-docs/build/html/detection/window.html

All the best,

**Comment by deepcharles** [comment]
Hello,

Indeed, window-sliding methods are online. Don't hesitate to use your custom cost function, as in 
[here](http://ctruong.perso.math.cnrs.fr/ruptures-docs/build/html/costs/costcustom.html), to fit your signals.

Cheers,
