### ISSUE TITLE
Some errors in the window method

### ISSUE THREAD

**Issue by yassineAlouini** [deepcharles/ruptures#30]
https://github.com/deepcharles/ruptures/blob/86140d08a9c210259346d7d61af713e3a65651e1/ruptures/detection/window.py#L258

Some minor errors in the `predict` method of the `window` algo: penalty arg should be pen and missing epsilon. 

If that works for you, I can make a PR this weekend. Let me know. :cat2:

**Comment by deepcharles** [comment]
Yes, that would be great. Many thanks.
