### ISSUE TITLE
Question: How do i use Ruptures to detect large  data streaming? 

### ISSUE THREAD

**Issue by nntp4** [deepcharles/ruptures#320]
## Description
I need to process more than 10 TB of data in Kafka clusters per day. 
In other words how do I use ruptures with the distributed system to process large data streaming?

**Comment by tg12** [comment]
This question doesn't make much sense. It's time to close the book on this one. I assume you're working on some Offline Change Point Detection project, but honestly, this isn't the place for it. Change point detection methods fall into two categories: online methods, which spot changes in real-time, and offline methods, which look back after all data is in. If you want to dive deeper, check out this Wikipedia page on change detection: https://en.wikipedia.org/wiki/Change_detection.

**Comment by nntp4** [comment]
@tg12 THX your reply,  I close this issue now
