### ISSUE TITLE
Link to documentation broken ?

### ISSUE THREAD

**Issue by ilyasst** [deepcharles/ruptures#33]
Hello,

I am trying to access the documentation of the rupture library from the README link but cannot reach it.
Is the documentation still available somewhere ?

Cheers,
Ilyass

**Comment by deepcharles** [comment]
The website host is performing some maintenance operations, but that takes longer than I expected.

Here is a temporary link to the documentation: [https://deepcharles.github.io/ruptures/](https://deepcharles.github.io/ruptures/)

**Comment by TMiguelT** [comment]
I wonder if github pages is a better long term solution anyway?
