### ISSUE TITLE
return value of predict in pelt

### ISSUE THREAD

**Issue by divyagupta25** [deepcharles/ruptures#37]
Hi,

I intend to detect change points in a uni-variate time sequence of length 49 using PELT search method. The values returned by predict are: [15, 20, 49]
The value of partition.keys() is [(0, 15), (15, 20), (20, 49)].
https://github.com/deepcharles/ruptures/blob/1a422fc9218c5625de7ac79b333021bd0cf83516/ruptures/detection/pelt.py#L181

I want to find the data points which have been detected as change points, and am not sure how to use this result. Are these indexes or positions? because they contain both 0 and 49

**Comment by deepcharles** [comment]
The change points are 15 and 20. The index 49 is returned by convention (because in most methods I need to access the length of the signal without having the signal).
`partition.keys()` contains the starts and ends of the three regimes: `signal[0:15]`, `signal[15:20]`, `signal[20:49]`.
