### ISSUE TITLE
example setting the penalty parameter?

### ISSUE THREAD

**Issue by wqp89324** [deepcharles/ruptures#4]
Is there an example about how to set the pen parameter for Pelt?

**Comment by deepcharles** [comment]
Hello,

Finding a proper value for the `pen` paper heavily depends on the signal at hand. As a rule of thumb, the more noise, samples or dimensions, the larger this parameter should be. 
For parametric changes (such as mean-shifts, scale-shifts,...), [the Bayesian Information Criterion](https://en.wikipedia.org/wiki/Bayesian_information_criterion) (BIC) is a good starting point. For instance, detecting mean-shifts with BIC yields:

```python
T, d = signal.shape  # number of samples, dimension
sigma = ...  # noise standard deviation
bic = sigma*sigma*np.log(T)*d
algo = rpt.Pelt().fit(signal)
my_bkps = algo.predict(pen=bic)
```

However, BIC tends to produce too low penalty values. When that happens, the simplest procedure, is to test several values, as below:

```python 
pen_values = np.logspace(0, 3, 10)  # for instance
algo = rpt.Pelt().fit(signal)
bkps_list = [algo.predict(pen=pen) for pen in pen_values]
# then compare elements of bkps_list
```

Cheers, 

Charles

**Comment by mylife126** [comment]
Hello thanks for sharing the BIC theory, however, could you please let me know why the way you calculate BIC is bic = sigma*sigma*np.log(T)*d  ?   In the Wiki, i could not find such derivation. Thanks!

**Comment by deepcharles** [comment]
Hello,

There might be a mistake indeed. The formula should be

<img src="https://render.githubusercontent.com/render/math?math=BIC=2\sigma^2\log(T)\times(d%2B+1)">

This is only valid for the cost function `l2` (see Table 1 of this [article](https://charles.doffy.net/files/sp-review-2020.pdf)). 
To verify it, assume the signal is multivariate Gaussian with isotropic variance $sigma^2$, use the normal formula for BIC and get rid of all terms that does not depend on $K$, the number of change points.

**Comment by deepcharles** [comment]
If you would like to correct it in the docs, do not hesitate to make a pull request ;)

**Comment by DPTPaul** [comment]
Hello,

Thanks a lot for this very useful package! 
I'm currently working on a signal and have no idea about the number of breakpoints. 
I understand that BIC approximation can only be used with a `l2` cost function. As I try to detect both mean and variance shifts, I would like to use a `rbf`` cost function. 

Is there any trick to set a good penalty value (or at least a sense of scale)?
