### ISSUE TITLE
Increase performance using a cached value

### ISSUE THREAD

**Issue by Nyandams** [deepcharles/ruptures#58]
Do you thing that caching some values instead of calling the cost functions all the time could help to improve the estimators execution speed? That could be a parameter such as 'jump'.

Story time:
Some times ago I tried to use the Pelt Estimator on a really large datasets (from thousands to millions of elements) to determine stagnation periods on a time series data. It was kinda slow and eventually the change point detection wasn't really what I needed in my case.

In order to do what I wanted, I created a small [library](https://github.com/Nyandams/step_detection) inspired by `ruptures` (I really learned a lot by reading the source code). And one day I tried to launch it on big datasets and it was also slow. I got the idea of doing a system of cache to not compute the cost function too many times and that helped me to reduce the execution time (more than 100 times faster) and allowed me to use my method on really big datasets. 

[Pull request of the caching](https://github.com/Nyandams/step_detection/pull/3) on my library. The structure of the code is similar to `ruptures`

Btw, thanks for that amazing library !

**Comment by deepcharles** [comment]
Hello, thanks for your kind comments.

I have looked at your code, and unless I am mistaken, `ruptures` already implements a similar cache strategy in Dynp and Pelt. 

See for instance:
https://github.com/deepcharles/ruptures/blob/b77f4fe32875947769c1b7c4f0fc6c56d576f53b/ruptures/detection/dynp.py#L84

Here, the method `.seg` is a cached version of [`._seg`](https://github.com/deepcharles/ruptures/blob/b77f4fe32875947769c1b7c4f0fc6c56d576f53b/ruptures/detection/dynp.py#L96) which computes the segmentation on all subsegments.
The cache strategy is implemented with [lru_cache](https://docs.python.org/3/library/functools.html#functools.lru_cache).

In my opinion, there are two ways to accelerate Dynp and Pelt (which I am currently working on):
- using Cython bindings,
- skipping the computation of some subsegments.

**Comment by Nyandams** [comment]
Thanks for the feedback,

Have you tried using [`Numba`](http://numba.pydata.org/)? that could also be a way to improve the performance speed. Some people told me that they use it on a modified version of of one of the exact method and it allowed to improve quite a lot the execution speed. I never used it but a simple decorator added to the functions allows to accelerate most of Python and Numpy code.

**Comment by deepcharles** [comment]
> Have you tried using Numba?

I have not, but I will give it a try. If you have an example, that would be great.
