### ISSUE TITLE
Allow other plot **kwargs for show.display to be set

### ISSUE THREAD

**Issue by dcdenu4** [deepcharles/ruptures#7]
In ruptures.show.display() there is no avenue to pass along other general plotting options. While a **kwargs argument is taken in, it only sets specific elements found (which isn't clear in the docs). I would propose allowing the subplot call to eat all the extra args. I think this would be easier than having to use the returned fig or ax after the fact.

before:
`fig, axarr = plt.subplots(n_features, figsize=figsize, sharex=True)`
after:
`fig, axarr = plt.subplots(n_features, figsize=figsize, sharex=True, **kwargs)`

Of course this would change the way that **kwargs is currently used with setting **linewidth**, **alpha**, etc... But maybe those could be more implicit and parsed out or a separate input parameter.

**Comment by deepcharles** [comment]
Indeed, this would be a better behaviour for the `display` function. Changing this now.

**Comment by deepcharles** [comment]
Actually there were a few mistakes in the code I proposed but it is correct now (00b64b6e8514da452b112b8760bd694c28e40a76)
