### ISSUE TITLE
Collaboration with sktime

### ISSUE THREAD

**Issue by mloning** [deepcharles/ruptures#75]
Hi @deepcharles, just saw your post on https://github.com/MaxBenChrist/awesome_time_series_in_python/pull/26?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDEyODM1Mzc1MzU6MjEwMjA0ODI%3D, I'm one of the core developers of [sktime](https://github.com/alan-turing-institute/sktime).

We haven't implemented any time series annotation functionality yet, but would certainly be interested in collaborating and trying out how well our time series classification module works with ruptures. 

FYI We've already added ruptures on our version of the list [here](https://www.sktime.org/en/latest/related_software.html).

**Comment by deepcharles** [comment]
hello @mloning, thanks for the message (and the mention on your list of related packages)!

That would be great indeed. I went through the documentation of sktime, and there is definitely room for some collaboration! Do you have something particular in mind?

On my side, I definitely plan on creating examples in the documentation of ruptures using sktime (however not before a couple of weeks, as I am working on other parts of the package right now).

**Comment by mloning** [comment]
Trying out how the two packages work together seems like a good starting point, please let us know if something doesn't seem right!

**Comment by deepcharles** [comment]
Perfect. I'll ping you whenever I start working on it.
