### ISSUE TITLE
Layman Question - Predict for mean-shift and variance-shift?

### ISSUE THREAD

**Issue by Rotario** [deepcharles/ruptures#79]
Hi,
Layman here - apologies if this is a stupid Q!
I've read through your paper, and a few others. 
I'm trying to fit to data (2 signals/dimensions) that has changepoints that may be any of: mean-shift + variance-shift, mean-shift, variance-shift. I do not know the number of changepoints.

I'm getting some good accuracy on all the mean shift changepoints using Pelt and BinSeg with L2 cost function. This cost function is also great because the BIC value works for penalty and there's no supervision required.

However, using L2 doesn't really catch the variance-shift points, instead Rank, rbf (slow) and L1 catch all the changes quite well. But the penalty for these cannot be calculated, as far as I can tell? So need supervision.

I've noticed, looking at the [R cpt package guide](http://members.cbio.mines-paristech.fr/~thocking/change-tutorial/RK-CptWorkshop.html) that cpt offers the methods: `var`, `mean`, and `meanvar` which I assume does what it says on the tin.
It's not immediately obvious which cost function to select to effectively catch these `meanvar` or mean + variance shifts, do you have any recommendations please?
Thanks
R

**Comment by deepcharles** [comment]
You could try this [cost function](https://centre-borelli.github.io/ruptures-docs/user-guide/costs/costnormal/). It detects changes in mean and var (assuming a Gaussian random variable but it still work when the model is mispecified).
For this cost function, you could also work out a BIC penalty.

In the coming weeks, I will add to the documentation an small tutorial on heuritics to calibrate the penalty value when the number of changes is unknown. 
Also, a faster version of the kernel (rbf) detection is almost ready to be added to the package (it is a C implementation of the current pure Python one).

Cheers,

**Comment by deepcharles** [comment]
Closing for now. Feel free to reopen if you have more questions.

**Comment by Rotario** [comment]
That's brill - thanks for the heads up, and yeah Rbf was taking ages.
Thanks!
