### ISSUE TITLE
Speed up L2 computation

### ISSUE THREAD

**Issue by TheDerivator** [deepcharles/ruptures#96]
I just want to suggest that you could speed up the computation of L2 cost by precomputing the cumulative sums, so that signal[start:end].sum() becomes equivalent to cumsum[end] -  cumsum[start], so you do lookups instead of actually summing. If you do the same for the squares and use the fomula Var(X) = E[X^2] - E[X]^2 that is enough to get to the sample variance.

Here is a sample implementation in the 1d case that worked about 4 times faster in my tests on a 80000 sample signal (35 vs 9 seconds)

```
class CostL2Fast(BaseCost):
    # The 2 following attributes must be specified for compatibility.
    model = "fastl2"
    min_size = 5

    def fit(self, signal):
        """Set the internal parameter."""
        self.signal = signal
        self.cs = np.r_[[0], signal.cumsum()]
        self.cs2 = np.r_[[0], np.power(signal, 2).cumsum()]
        return self

    def error(self, start, end):
        """Return the approximation cost on the segment [start:end].

        Args:
            start (int): start of the segment
            end (int): end of the segment

        Returns:
            float: segment cost
        """
        n = end - start
        # More efficient computation of the variance based on the cumsums of the values and the values squared
        return (self.cs2[end] - self.cs2[start]) - ((self.cs[end] - self.cs[start]))**2 / n
```

**Comment by deepcharles** [comment]
yes that would be great. Do you mind making a pull request? There is a contributing guide [here](https://centre-borelli.github.io/ruptures-docs/contributing/) (still under construction).
