### ISSUE TITLE
Add sponsor button

### ISSUE THREAD

**Issue by GuillaumeWrobel** [deepcharles/ruptures#98]
WDYT about adding a Sponsor button to this repo?

It's done by adding a funding file and enabling the right setting:
https://help.github.com/en/articles/displaying-a-sponsor-button-in-your-repository#displaying-a-sponsor-button-in-your-repository

Thank you again for the hard and appreciated work.

**Comment by deepcharles** [comment]
Thanks for your suggestion. We are currrently considering it!
